# Generated by Django 3.2.17 on 2023-02-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='name1',
        ),
    ]
